defaults: &defaults
  database:
    mysql:
      user: "root"
      password: "iamjay"
      dbname: "consume_development"
  mobile:
    os:
      android:
        version: "0.1"
        describtion: "consume.solife.us"
        url: "http://solife-apk.qiniudn.com/iconsumes-0.1.apk"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
