development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: consume_development
  pool: 5
  username: root
  password: iamjay
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: consume_test
  pool: 5
  username: root
  password: iamjay
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: consume_production
  pool: 5
  username: root
  password: iamjay
  host: localhost
